# File: all_page_data.py
# 
# This file was written by AllPageData.save_next().

all_page_titles = OrderedDict([
    ('Agonist (Receptor Agonist)', 'agonist.html'),
    ('Antagonist (Receptor Antagonist)', 'antagonist.html'),
    ('Classical Stimulants', 'classical_stimulants.html'),
    ('Cocaine', 'cocaine.html'),
    ('Escitalopram (Lexapro)', 'lexapro.html'),
    ('Dextroamphetamine (Dexedrine)', 'dexedrine.html'),
    ('Dopamine (DA)', 'dopamine.html'),
    ('Endogenous Opioids', 'endogenous_opioids.html'),
    ('GABA', 'gaba.html'),
    ('Glutamate (Glu)', 'glutamate.html'),
    ('Heart Terminology', 'heart_terminology.html'),
    ('Heroin', 'heroin.html'),
    ('Welcome to the Drug Education and Harm Reduction Website', 'index.html'),
    ('Methamphetamine', 'methamphetamine.html'),
    ('Norepinephrine (NE)', 'norepinephrine.html'),
    ('Receptor', 'receptor.html'),
    ('Serotonin (5-HT)', 'serotonin.html'),
    ('Sudden Cardiac Death', 'sudden_cardiac_death.html'),
    ('Test Page 01 (This Is the Title)', 'test_page_01.html'),
])

all_page_aliases = OrderedDict([
    ('agonist (receptor agonist)', 'agonist.html'),
    ('agonist', 'agonist.html'),
    ('antagonist (receptor antagonist)', 'antagonist.html'),
    ('antagonist', 'antagonist.html'),
    ('classical stimulants', 'classical_stimulants.html'),
    ('classical_stimulants', 'classical_stimulants.html'),
    ('classical stimulant', 'classical_stimulants.html'),
    ('cocaine', 'cocaine.html'),
    ('crack', 'cocaine.html'),
    ('crack cocaine', 'cocaine.html'),
    ('coke', 'cocaine.html'),
    ('escitalopram (lexapro)', 'lexapro.html'),
    ('deprecated_lexapro', 'deprecated_lexapro.html'),
    ('dextroamphetamine (dexedrine)', 'dexedrine.html'),
    ('dexedrine', 'dexedrine.html'),
    ('dextrostat', 'dexedrine.html'),
    ('dextroamphetamine', 'dexedrine.html'),
    ('d-amphetamine', 'dexedrine.html'),
    ('s-amphetamine', 'dexedrine.html'),
    ('(+)-amphetamine', 'dexedrine.html'),
    ('s-(+)-amphetamine', 'dexedrine.html'),
    ('dexamphetamine', 'dexedrine.html'),
    ('dextroamphetamine sulfate', 'dexedrine.html'),
    ('dopamine (da)', 'dopamine.html'),
    ('dopamine', 'dopamine.html'),
    ('da', 'dopamine.html'),
    ('endogenous opioids', 'endogenous_opioids.html'),
    ('endogenous_opioids', 'endogenous_opioids.html'),
    ('endorphin', 'endogenous_opioids.html'),
    ('enkephalin', 'endogenous_opioids.html'),
    ('dynorphin', 'endogenous_opioids.html'),
    ('endogenous morphine', 'endogenous_opioids.html'),
    ('endorphins', 'endogenous_opioids.html'),
    ('gaba', 'gaba.html'),
    ('gamma-aminobutyric acid', 'gaba.html'),
    ('glutamate (glu)', 'glutamate.html'),
    ('glutamate', 'glutamate.html'),
    ('glu', 'glutamate.html'),
    ('glutamic acid', 'glutamate.html'),
    ('heart terminology', 'heart_terminology.html'),
    ('heart_terminology', 'heart_terminology.html'),
    ('heart attack', 'heart_terminology.html'),
    ('heart attacks', 'heart_terminology.html'),
    ('myocardial infarction', 'heart_terminology.html'),
    ('myocardial infarctions', 'heart_terminology.html'),
    ('mi', 'heart_terminology.html'),
    ('arrhythmia', 'heart_terminology.html'),
    ('arrhythmias', 'heart_terminology.html'),
    ('ventricular tachycardia', 'heart_terminology.html'),
    ('supraventricular tachycardia', 'heart_terminology.html'),
    ('tdp', 'heart_terminology.html'),
    ('torsades', 'heart_terminology.html'),
    ('torsades de pointes', 'heart_terminology.html'),
    ('fibrillation', 'heart_terminology.html'),
    ('ventricular fibrillation', 'heart_terminology.html'),
    ('heroin', 'heroin.html'),
    ('diacetylmorphine', 'heroin.html'),
    ('diamorphine', 'heroin.html'),
    ('smack', 'heroin.html'),
    ('horse', 'heroin.html'),
    ('welcome to the drug education and harm reduction website', 'index.html'),
    ('index', 'index.html'),
    ('lexapro', 'lexapro.html'),
    ('cipralex', 'lexapro.html'),
    ('escitalopram', 'lexapro.html'),
    ('s-citalopram', 'lexapro.html'),
    ('methamphetamine', 'methamphetamine.html'),
    ('desoxyn', 'methamphetamine.html'),
    ('desoxyephedrine', 'methamphetamine.html'),
    ('n-methylamphetamine', 'methamphetamine.html'),
    ('meth', 'methamphetamine.html'),
    ('methedrine', 'methamphetamine.html'),
    ('vicks vapor inhaler', 'methamphetamine.html'),
    ('crystal', 'methamphetamine.html'),
    ('d-methamphetamine', 'methamphetamine.html'),
    ('l-methamphetamine', 'methamphetamine.html'),
    ('levmetamfetamine', 'methamphetamine.html'),
    ('norepinephrine (ne)', 'norepinephrine.html'),
    ('norepinephrine', 'norepinephrine.html'),
    ('ne', 'norepinephrine.html'),
    ('noradrenaline', 'norepinephrine.html'),
    ('receptor', 'receptor.html'),
    ('receptors', 'receptor.html'),
    ('serotonin (5-ht)', 'serotonin.html'),
    ('serotonin', 'serotonin.html'),
    ('5-ht', 'serotonin.html'),
    ('5-hydroxytryptamine', 'serotonin.html'),
    ('sudden cardiac death', 'sudden_cardiac_death.html'),
    ('sudden_cardiac_death', 'sudden_cardiac_death.html'),
    ('test page 01 (this is the title)', 'test_page_01.html'),
    ('test_page_01', 'test_page_01.html'),
])
